logging:
  level:
    root: WARN
    br.com.home.automateservice: INFO
  pattern:
    console: '%msg%n'
    file: '%msg%n'

server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: kafka-bootstrap.home.lab:9092, 192.168.1.211:9092
    properties[spring.kafka.bootstrap-servers]: kafka-bootstrap.home.lab:9092, 192.168.1.211:9092
    topic: automate-events-dev

    producer:
      compression-type: lz4
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: all
      batch-size: 16384
      linger-ms: 5
      request-timeout-ms: 60000
      retries: 5
      properties:
        schema:
          registry:
            url: http://192.168.1.225:8081
        auto:
          register:
            schemas: true
  main:
    allow-bean-definition-overriding: true